we_service:
    resource: "@WeServiceBundle/Controller/"
    type:     annotation

weservicewebservice:
    resource: "@weservicewebserviceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
