services:
#    weservicewebservice.example:
#        class: weservice\webserviceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  we.service.authuser:
    class: We\Service\Authentication